directory: ~/.homebase # where your data will be stored
httpMirror: true       # enables http mirrors of the dats
ports:
  http: 80             # HTTP port for serving
#letsencrypt:           # set to false to disable lets-encrypt
#  email: bob@foo.com   # you must provide your email to LE for admin
#  agreeTos: true       # you must agree to the LE terms (set to true)

# Note: exposes a web-page that's available *without* authentication and has your hyper and dat urls on it.
#dashboard:             # set to false to disable
#  port: 8089           # port for accessing the metrics dashboard

# enter your pinned hyperdrives here
hyperdrives: []               # `[]` for empty list. Remove the `[]` if you have hyperdrives listed
#- url: hyper://1f968afe867f06b0d344c11efc23591c7f8c5fb3b4ac938d6000f330f6ee2a03/
#  domains:
#  - mysite.com
#  - my-site.com
#- url: 868d6000f330f6967f06b3ee2a03811efc23591afe0d344cc7f8c5fb3b4ac91f
#  domain:
#  - othersite.com

# enter any proxied routes here
proxies: []            # `[]` for empty list. Remove the `[]` if you have proxies listed
#- from: myproxy.com
#  to: https://mysite.com/
#- from: foo.proxy.edu
#  to: http://localhost:8080/
#- from: best-proxy-ever
#  to: http://127.0.0.1:123/

# enter any redirect routes here
redirects: []          # `[]` for empty list. Remove the `[]` if you have proxies listed
#- from: myredirect.com
#  to: https://mysite.com/
#- from: foo.redirect.edu
#  to: http://localhost:8080/
#- from: best-redirect-ever
#  to: http://127.0.0.1:123/
